language: go

services:
  - docker

before_install:
  - ./test-docker.sh detach

install:
  - go get github.com/mholt/caddy
  - rm -rf $GOPATH/src/github.com/mholt/caddy/vendor
  - go get -u -t

script:
  - go vet
  - go test -v -cover -race