language: go

services:
  - docker

before_install:
  - ./test-docker.sh detach
  - export GO111MODULE="on"

install:
  - go mod vendor

script:
  - go vet -mod vendor
  - go test -v -cover -race -mod vendor